[Settings]
EnableTrim=1

; TrimIntervalMs: Interval between memory trims (default 10000ms).
TrimIntervalMs=10000

EnablePriorityFix=1

; PriorityClass: 0=Idle, 1=BelowNormal, 2=Normal (default), 3=AboveNormal, 4=High
PriorityClass=2

EnableThreadPriorityFix=1

; RawInputMode: 0=Disabled, 1=Suspend thread, 2=Zeroing, 3=Zeroing+Throttle
RawInputMode=1

; RawInputSleepMs: Throttle per call for mode 3 (default 10ms)
RawInputSleepMs=1500

; RawInputPatchDelayMs: Delay before patching IAT (default 10000ms)
RawInputPatchDelayMs=10000
